apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: createbuckets
  name: createbuckets
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: createbuckets
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: createbuckets
    spec:
      containers:
        - command:
            - /bin/sh
            - -c
            - ' /usr/bin/mc alias set myminio http://minio:9000 admin password; /usr/bin/mc mb myminio/syslog-bucket; /usr/bin/mc policy set public myminio/syslog; exit 0; '
          image: minio/mc
          name: createbuckets
          resources: {}
      restartPolicy: Always
status: {}
