apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: fluent-bit
  name: fluent-bit
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fluent-bit
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: fluent-bit
    spec:
      containers:
        - env:
            - name: AWS_ACCESS_KEY_ID
              value: admin
            - name: AWS_SECRET_ACCESS_KEY
              value: password
          image: fluent/fluent-bit:2.0.4
          name: fluent-bit
          ports:
            - containerPort: 5140
          resources: {}
          volumeMounts:
            - mountPath: /fluent-bit/etc/fluent-bit.conf
              name: fluent-bit-claim0
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: fluent-bit-claim0
          persistentVolumeClaim:
            claimName: fluent-bit-claim0
            readOnly: true
status: {}
